# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
---
_extends: .github
tag-template: ssh-$NEXT_PATCH_VERSION
name-template: $NEXT_PATCH_VERSION
version-template: $MAJOR.$MINOR.$PATCH
